### ISSUE TITLE
Customizer - Layout Section

### ISSUE THREAD

**Issue by DustinHartzler** [woothemes/storefront#240] opened 2015-09-29 13:35 UTC
The Layout section of the Customizer looks a bit wonky on Windows Chrome and Firefox

![image](https://cldup.com/JhPcQiKC05.PNG)

**Comment by jameskoster** [comment] 2015-10-05 12:57
Think this might be a WP style thing. Which version are you using? Looking fine here on 4.3.1; https://cloudup.com/cOMxr3AM7Ux

**Comment by DustinHartzler** [comment] 2015-10-09 13:27
It might be related to the **Storefront WooCommerce Customiser** plugin. I'm waiting to hear back. If it is, I can report the bug there :)

**Comment by jameskoster** [comment] 2015-10-13 17:14
I think this is likely the WP version. Please also check they're running the latest version.

**Comment by jameskoster** [comment] 2015-10-26 11:33
Going to close this one as I've not seen it reported elsewhere and cannot reproduce. If you figure out the exact cause please feel free to re-open.

**Closed by jameskoster** 2015-10-26 11:33 UTC
