### ISSUE TITLE
Automatic Updating for Storefront

### ISSUE THREAD

**Issue by BurlesonBrad** [woothemes/storefront#338] opened 2016-03-01 15:28 UTC
Howdy @jameskoster !
I finally pecked around, rubbed all my cranium cells together really fast, generated enough brainwaves, and figured out **_why_** and **_how_** WooCommerce beta can get updated to the latest git via your [plugin](https://github.com/woothemes/woocommerce-beta-tester).  _(It's a php class in the header)_

So...(apparently) to make the same magic happen with Storefront so that someone can install a "Storefront Beta" plugin and get updates, there would need to be a modification added to the official git of Storefront (not a fork of Storefront, the real one).   

I'm about One Gazillion percent sure that you already know all this, but... Here's the deal ~ If I really want to get a "Storefront Beta" Plugin going here's what has to happen:

- [ ] I have to stare at the WooCommerce Beta plugin long enough to figure it out.  (ok, I think I've arrived at the "figure it out" part)
- [ ]  I need to do a pull, add the right lines, and then you'd have to merge it, right? (I get version control. I just don't get ....well... the "how-to" in Github)
- [ ] Then I need to make sure that my "Storefront Beta" plugin actually matches the same line that you merged into Storefront
- [ ] Then I need to upload this "Storefront Beta" to Git or [.org/plugins/add/](https://wordpress.org/plugins/add/)

All that's cool, fine, yee-haw, rock on, and dandy.  But, when the Koster Cranium sits down at the computer vs. when the Brad Brain sits down at the computer there's a slight ( ok, **HUGE!**) difference in the actual time needed to create something.

If I can do this, will you merge the fork? and / or Tell me what you'd want the thingymajig to be called? I figured "SF_Beta_Tester" would work.  But, again, it'd really help on my efficiency if you'd just go ahead, pick a name, and let me know.  Then I'll follow [these instructions](https://github.com/woothemes/storefront/blob/master/CONTRIBUTING.md#how-to-submit-a-pr) and send it back up to 'ya.

**Comment by jameskoster** [comment] 2016-03-02 09:22
@BurlesonBrad We'll definitely consider it :) Please go ahead and send the pull request and we'll evaluate accordingly.

I'd probably use `Storefront_Beta_Tester` for the class name in your plugin.

**Comment by BurlesonBrad** [comment] 2016-03-02 18:58
well.... So far, here's where I'm at:

https://github.com/BurlesonBrad/storefront-beta/blob/master/storefront-beta.php

Feel free to jump in, laugh your ass off, contribute, or tell me to take a hike.
Either way ~ **I started!**

**Comment by seb86** [comment] 2016-03-03 17:05
Just pushed the start of the Storefront Beta Tester. It uses the theme update API hooks instead. Now we just need a beta version of Storefront released to see it in action and tweak if needed.

https://github.com/seb86/Storefront-Beta-Tester

**Comment by BurlesonBrad** [comment] 2016-03-03 17:08
@seb86 , if you'll do a pull request, add the appropriate header info, then tag @jameskoster in this thread, he'll check it over, then merge the pull :+1:

**Comment by seb86** [comment] 2016-03-03 17:10
@BurlesonBrad A pull request on this repo? I thought this was going to be a separate plugin?

**Comment by BurlesonBrad** [comment] 2016-03-03 17:13
@seb86 do a pull request on the STOREFRONT theme. The theme needs to have specific header info added right?  _I can totally be missing something_  But, doesn't the theme have to have specific headers in it that connect to the beta updater plugin?

**Comment by seb86** [comment] 2016-03-03 17:16
@BurlesonBrad I don't think so no. It just reads the information from the style.css file like a plugin. All the information is already there. What header info do you think needs to be added?

**Comment by seb86** [comment] 2016-03-03 17:23
@jameskoster We just need your feedback on the beta tester plugin. Let us know what needs tweaking, if any. You have been added to the repo also should you need to push to it yourself you can.

**Comment by BurlesonBrad** [comment] 2016-03-03 17:27
@seb86 , If you read over that documentation and the notes over on my initial attempt at the plugin, you'll notice in the notes here: https://github.com/BurlesonBrad/storefront-beta/blob/master/notes.txt that in order for [Andy's Updater](https://github.com/afragen) to work, look at these requirements:
https://github.com/afragen/github-updater#themes

these two lines *MUST* be in the theme that the "updater plugin" is trying to pull _*from*_
```
GitHub Theme URI: https://github.com/woothemes/storefront
GitHub Branch:    master
```

So, someone: You, me, @jameskoster or anyone else for that matter, simply needs to pull, add the two additional lines mentioned above and *[HERE](https://github.com/afragen/github-updater#themes)*, then @jameskoster can look over the request and merge.  

Does that make sense?

**Comment by seb86** [comment] 2016-03-03 17:32
@BurlesonBrad So what you want is really a bleeding edge tester that checks the repo for any changes and not a beta release like they have done with WooCommerce, correct?

**Comment by seb86** [comment] 2016-03-03 17:36
@BurlesonBrad From you notes, what you are suggesting is to add a new header so you can use the GitHub Updater.

**Comment by seb86** [comment] 2016-03-03 17:38
@BurlesonBrad What I have done is an actual beta tester plugin for Storefront similar to the WooCommerce Beta Tester. Once WooThemes have released a new beta release of Storefront, the plugin will notify the user that a beta update is available.

**Comment by BurlesonBrad** [comment] 2016-03-03 17:39
um..... YEP!  :+1: 
and that's exactly what I've done here:
https://github.com/BurlesonBrad/storefront/blob/master/style.scss#L11

Right. So, when someone goes to change the padding, change the php files, or do anything else, there's a notification & the updater plugin will run back over to git and grab those newer files with all those changes.

**Comment by seb86** [comment] 2016-03-03 17:44
@BurlesonBrad OK, so rather than adding new headers. I suggest that there is a settings page where the user can select either beta releases or night bleeding edge version of the theme. Much like the WordPress Beta Tester.

Then once that option is identified the plugin will update based on that option. If the user selects night builds then the GitHub repo is checked for commits and does a pull request for those changes.

So I have started it off for beta releases. You can start by adding the settings page and we can go from there.

**Comment by BurlesonBrad** [comment] 2016-03-03 17:51
It's not just about looking for & checking the _*version number*_ in the master zipball of SF's git repo!

@seb86 That would leave a person with a notification of 2.0 being the "latest beta" version, when in all reality @jameskoster [cranks out hundreds of changes](https://github.com/woothemes/storefront/commits/master) to the "2.0 version" faster than a pissed off bull who realizes there is another syringe of medicine waiting for him!

The goal is to be able to find a way to have all of his _(or anyone else's)_  [commits](https://github.com/woothemes/storefront/commits/master) to be pushed to the individual's SF instance.

**Comment by seb86** [comment] 2016-03-03 17:54
@BurlesonBrad I didn't say anything about checking the version number in the master zipball. I said check for commits but only if the user has selected to have updates of the nightly builds and not a release.

**Comment by BurlesonBrad** [comment] 2016-03-03 17:55
Ok, I like that [above mentioned idea](https://github.com/woothemes/storefront/issues/338#issuecomment-191881013)
The girls need to be picked up in an hour, and I've already got a work 'to-do' list a mile long, then tonight the wife and I are going to a Domestic Violence awareness gala thing.
If I can get to adding a settings page tonight, I will.

**Comment by seb86** [comment] 2016-03-03 17:55
@BurlesonBrad There are more than one way of using GitHub to your advantage.

**Comment by jameskoster** [comment] 2016-03-03 17:59
Just FYI, I unfortunately don't really have time to work on this myself, but am happy to test and merge stuff if necessary.

**Comment by BurlesonBrad** [comment] 2016-03-03 18:07
I'm diggin that idea.  Now.... for me to hen peck this code into the plugin:
https://github.com/sheabunge/wordpress-beta-tester/blob/master/wp-beta-tester.php#L149-L202

@seb86 double check me on this, but those above mentioned lines are the correct one's right?

**Comment by seb86** [comment] 2016-03-03 18:13
@jameskoster That sounds great James. Thank you.

**Comment by seb86** [comment] 2016-03-03 18:13
@BurlesonBrad Yes, those lines are correct.

**Comment by BurlesonBrad** [comment] 2016-03-03 19:27
This'll probably be my last entry for a while, but @seb86 ....
While these options are great, we're still not actually hooking into the right thing to get the notification.  Instead of hooking into anything WordPress / Storefront, I think we're going to have to hook into something *_GIT_* related.  Git sends notifications for changes in a repo. I think those are what we need to latch onto in order for the updater to actually work correctly with a notification for each Commit to Storefront.  Here, check this video:
[http://screencast-o-matic.com/watch/cDeeqc1lxz](http://screencast-o-matic.com/watch/cDeeqc1lxz)
https://developer.github.com/v3/activity/notifications/

**Comment by seb86** [comment] 2016-03-03 20:50
@BurlesonBrad I watched your screencast. I understand what you want. The settings page from the WordPress Beta Tester would not just be copied and pasted. Obviously it would be tweaked for the Storefront Beta Tester.

The options would be:

- Beta release ()
- Constantly developed on a.k.a Nightly Builds ()

When the nightly build is selected then the plugin will check for a new commit and when it has been detected from the GitHub repo, that commit sha would be stored for like X amount of time so the updater is not constantly nugging you a notification every 5 minutes because of the amount of commits that have been pushed in such a short window.

When it is time to check again it will compare if the last commit stored has changed from the latest commit on GitHub. If it is new then that commit sha would be stored and the user will be notified that a new update exists.

The user is then able to update Storefront which then pulls everything new since the last commit.

I would recommend adding the settings page to the "Tools" section the same as WordPress Beta Tester.

I have created a new branch on my repo called "[Settings Page](https://github.com/seb86/Storefront-Beta-Tester/tree/Settings-Page)" where you can manage that when you have more free time.

It is not the Git notifications that we would need to use. It would be the repo commit history that we would need to fetch.

I actually had some help in a previous project last year with fetching a chosen branch from a certain commit entry point which would be good for this project so I will look that up and apply it to the plugin when I have a bit more time.

Hope that made things a lot clear for you Brad.

**Comment by seb86** [comment] 2016-03-03 20:51
@jameskoster I think the [Storefront Beta Tester](https://github.com/seb86/Storefront-Beta-Tester) is ready as it is for just simple beta releases but we would only be able to confirm properly once you are ready for a beta release of version 2 of Storefront.

**Comment by seb86** [comment] 2016-03-03 21:00
@BurlesonBrad This is what we would need to find the latest commit. https://developer.github.com/v3/repos/#get-branch where would need to store the **sha**

Then when the update button has been pressed, we do something like this: `git clone %s %s", escapeshellarg( 'master' ), escapeshellarg( 'themes/storefront' ) ), $output, $return );`

**Comment by jameskoster** [comment] 2016-03-04 09:52
@seb86 What does the plugin look for? I'm assuming a tag with a specific naming style? `2.0.0-beta`?

**Comment by mattyza** [comment] 2016-03-04 10:15
Agreed, @jameskoster. I'd suggest we close this issue out and have the beta tester plugin uploaded to WordPress.org as a way to use the "bleeding edge" version of Storefront (aka. `master` branch).

@BurlesonBrad @seb86

**Comment by jameskoster** [comment] 2016-03-04 10:54
Yup, if we don't need to do anything to Storefront core to facilitate this, let's close the issue.

**Comment by seb86** [comment] 2016-03-04 11:11
@jameskoster @mattyza I will submit the plugin to WordPress.org so users can start to beta test Storefront.

@BurlesonBrad Had wanted another possible option that allows users to up date when ever a commit has been submitted to the Storefront repo rather than just a tagged release. I guess we can add that to the beta tester for another time and move forward with what I have done for now. What do you guys think?

**Comment by jameskoster** [comment] 2016-03-04 11:28
I reckon the plugin is good to go for now. The nightly build support could come in version two. That's really up to you guys.

**Closed** 2016-03-04 13:10 UTC
Labels: [Priority] Low, [Type] Enhancement

**Comment by seb86** [comment] 2016-03-04 13:21
@BurlesonBrad @jameskoster @mattyza I have submitted the plugin to WordPress.org

Just need to await approval now. When can we expect to beta test version 2?

**Comment by seb86** [comment] 2016-03-06 16:32
@jameskoster WordPress.org denied the approval of the Storefront Beta Plugin. It is in clear violation of the rules. 

> We don't allow these. Not even for Automattic. Which is kind of funny and they should know that. - Mika Epstein

You will either have to contact them directly to see if they will make an exception or link the beta plugin somewhere in the Storefront theme for developers to download the beta tester directly from GitHub.

**Comment by jameskoster** [comment] 2016-03-07 10:19
I'm sure the WooCommerce Beta Tester plugin was live on .org just the other day? OK, np, we can add a link to the readme. I'll open a new issue.

**Comment by shivapoudel** [comment] 2016-03-07 10:52
@jameskoster Does the Beta tester plugin compile SCSS stylesheet or need to regenerate :)

**Comment by jameskoster** [comment] 2016-03-07 11:03
@shivapoudel The Storefront one? I believe it grabs the latest tag, so the css is all included.

@seb86 I'd like to have the beta ready for the end of the month.

**Comment by seb86** [comment] 2016-03-07 13:08
@jameskoster The first version of the beta plugin should be ready. Just needs to be confirmed. I will do a test on a fork repo just to check.
