### ISSUE TITLE
Custom CSS in Child Theme does not work

### ISSUE THREAD

**Issue by todorchrisov** [woothemes/storefront#261] opened 2015-10-31 19:24 UTC
After upgrading to Storefront 1.5.2 all my custom CSS tweaks in my child theme are not working anymore.

**Comment by Opportus** [comment] 2015-10-31 20:45
Same bug for me.

**Comment by S4Mi** [comment] 2015-11-01 11:30
same here

**Comment by WPprodigy** [comment] 2015-11-01 14:07
This is likely the cause: https://github.com/woothemes/storefront/commit/7299ab63881afb6848a56f8163e786e0b2cbd3b7

Be sure to enqueue your child themes stylesheet. See: https://codex.wordpress.org/Child_Themes

**Comment by jameskoster** [comment] 2015-11-01 14:35
@todorchrisov @Opportus @S4Mi sorry about this. To fix, open /inc/functions/setup.php and find;

`wp_enqueue_style( 'storefront-style', get_template_directory_uri() . '/style.css', '', $storefront_version );`

after it please add

`wp_enqueue_style( 'storefront-child-style', get_stylesheet_uri(), '' );`

That should fix the issue. Let me know if it does and I'll put the update to .org.

**Comment by Opportus** [comment] 2015-11-01 23:51
If I understand what you say, the code should look like this:

    if ( ! is_child_theme() ) {
		// If a child theme's not loaded, just load the stylesheet as usual.
		wp_enqueue_style( 'storefront-style', get_stylesheet_uri(), '', $storefront_version );
	} else {
		// If a child theme is loaded, load the parent theme styles as normal (includes rtl) as well as the child themes style.css file.
		wp_enqueue_style( 'storefront-style', get_template_directory_uri() . '/style.css', '', $storefront_version );
		wp_enqueue_style( 'storefront-child-style', get_stylesheet_uri(), '' );
	}

For me, it just loads my child theme style after the parent style.
If I remove this line:
    wp_enqueue_style( 'storefront-style', get_template_directory_uri() . '/style.css', '', $storefront_version );
The storefront customizer style still overrides my child theme style.

**Comment by jameskoster** [comment] 2015-11-02 10:05
> For me, it just loads the child theme style after the parent style, conflicting each other.

I think it is expected behaviour that the parent css is loaded.

We have to load the parent styles for the RTL css to be included. If you don't want to include the parent css you should dequeue that manually in your child theme. We can document this.

> wp_enqueue_style( 'storefront-style', get_template_directory_uri() . '/style.css', '', $storefront_version );
The storefront customizer style does not load anymore.

It won't do. A lot of the styles are appended to that stylesheet. If it's not there, the styles don't get appended. TBH, removing the parent css entirely isn't really recommended. At that point you'd probably be better off creating your own custom parent theme.

**Comment by MonikaTS** [comment] 2015-11-02 11:21
I update storefront (parent) 
change storefront/inc/functions/setup.php after line 151
 I added
wp_enqueue_style( 'storefront-child-style', get_stylesheet_uri(), '' );

delete wp_enqueue styles in my child theme, 
html header child-theme:

<link rel='stylesheet' id='storefront-style-css'  ................ /> 
<style id='storefront-style-inline-css' type='text/css'> 
...
</style>
<link rel='stylesheet' id='storefront-child-style-css'  .. 
<link rel='stylesheet' id='storefront-woocommerce-style-css'......
<style id='storefront-woocommerce-style-inline-css' type='text/css'>
..
</style>

I can design  woo-commerce styles via css  in my child-theme,
but with this style-order I have to use a very strange cascade and this is bad for performance :(

in a perfect world :-) child-css is loading last, after all woo-commerce styles 

and I agree, child css shouldn't be enqueued from parent theme => in a perfect world

**Comment by todorchrisov** [comment] 2015-11-02 11:38
Thaks for all your efforts and feedback, @jameskoster !

Regretfully, I am totally lost with this new custom code. I pray for an update which will revert back the old functionality of Storefront where everything was nice and easy with custom css.

**Comment by jameskoster** [comment] 2015-11-02 11:57
Thanks @MonikaTS. OK, looks like we might need a new function here. I'll update shortly.

**Comment by jameskoster** [comment] 2015-11-02 12:16
@MonikaTS would you be able to give that a try? ^^

**Comment by MonikaTS** [comment] 2015-11-02 12:25
yes what should I do :-)

**Comment by jameskoster** [comment] 2015-11-02 12:29
@MonikaTS 

1. overwrite your copy of storefront/inc/structure/hooks.php with: https://github.com/woothemes/storefront/blob/17b69e67bc024b546f0e5f51a76f023cc20b32be/inc/structure/hooks.php

2. overwrite your copy of storefront/inc/functions/setup.php with: https://github.com/woothemes/storefront/blob/17b69e67bc024b546f0e5f51a76f023cc20b32be/inc/functions/setup.php

The child theme CSS should now be loaded after the WooCommerce css.

**Comment by MonikaTS** [comment] 2015-11-02 12:49
:-) you are the hero of the day => and it is monday (=murpheys day)
yes child css is loading last, before the first js

**Comment by jameskoster** [comment] 2015-11-02 12:52
OK. I will leave this a few hours to give others an opportunity to contribute. Otherwise I'll prepare the update tomorrow morning.

**Comment by Opportus** [comment] 2015-11-02 13:33
@jameskoster 

>We have to load the parent styles for the RTL css to be included. If you don't want to include the parent css you should dequeue that manually in your child theme. We can document this.

If I dequeue it manually from my child theme with:

    wp_dequeue_style( 'storefront-style' );

The style id "storefront-style-inline-css" (which, I think, is containing the storefront customizer style) still doesn't load...
Which lead to the same results as when I removed (for test purposes) :

    wp_enqueue_style( 'storefront-style', get_template_directory_uri() . '/style.css', '', $storefront_version );

in the storefront setup.php.

**Comment by jameskoster** [comment] 2015-11-02 16:23
@Opportus if you want to disable the Storefront core CSS but still have the Customizer controlled css load you'll need to attach it to a different stylesheet. You can see how it's included in core here; https://github.com/woothemes/storefront/blob/master/inc/customizer/display.php#L206

Your best bet would be to plug that function (`storefront_add_customizer_css()`). Essentially copy and paste it into your child theme but change the handle that `wp_add_inline_style()` references on line 206 to match your own stylesheet instead of `storefront-style`.

**Comment by ereckers** [comment] 2015-11-02 18:06
@jameskoster I tested your fix in comment 4 and it does work. However, since this is a new conditional in `setup.php`, it leads to loading the storefront-style twice for those of us enqueuing the storefront stylesheet in our `functions.php` file, ie.:

```
wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css', array(), $VER );
```

So, it would be a 2 step fix for me:

1. adding your fix in setup.php
2. removing my wp_enqueue_style of the storefront stylesheet from my `functions.php` file

**Comment by Opportus** [comment] 2015-11-02 22:20
Thanks @jameskoster.

>If you want to disable the Storefront core CSS but still have the Customizer controlled css load you'll need to attach it to a different stylesheet. You can see how it's included in core here; https://github.com/woothemes/storefront/blob/master/inc/customizer/display.php#L206
Your best bet would be to plug that function (storefront_add_customizer_css()). Essentially copy and paste it into your child theme but change the handle that wp_add_inline_style() references on line 206 to match your own stylesheet instead of storefront-style.

This will probably fix the case for those of us **not** enqueuing the storefront stylesheet in our child theme.

However, I wonder which direction will take the next update... do we have to adapt to this new behavior which, from what I understand, is the good practice, or will you revert back to the 1.5.1 behavior ?

**Comment by smcjones** [comment] 2015-11-03 07:41
I disagree with the logic of removing the child theme functionality from `hooks.php`. WordPress' documentation states that most themes will automatically load a child theme. Why is this not happening in Storefront? I think it *should* happen as per WordPress Codex expectations.

https://codex.wordpress.org/Child_Themes

**Comment by smcjones** [comment] 2015-11-03 07:45
In any case, for those still struggling, this code from the same page I referenced above in your `functions.php` child theme file should take care of issues:


    function theme_enqueue_styles() {

        $parent_style = 'parent-style';

        wp_enqueue_style( $parent_style, get_template_directory_uri() . '/style.css' );
        wp_enqueue_style( 'child-style',
            get_stylesheet_directory_uri() . '/style.css',
            array( $parent_style )
        );
    }
    add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );

**Comment by jameskoster** [comment] 2015-11-03 10:11
Closing this, should be fixed by https://github.com/woothemes/storefront/commit/17b69e67bc024b546f0e5f51a76f023cc20b32be

**Closed by jameskoster** 2015-11-03 10:11 UTC

**Comment by pelachile** [comment] 2016-06-01 03:38
I don't want any of the storefront styles in my theme. I just want the parent theme functionality. However, I cannot disable the storefront styles, from my child theme's functions file. I have dequeued them, and them deregistered them but to no avail. The only way I can disable them is to actually comment out the code that loads them in the actual storefront theme code and I hate that. I also want to remove all inline styles from the head as well. 

There has got to be a way to disable the parent styles from the child theme without having to touch the parent theme code.

**Comment by ArcodeFire** [comment] 2016-07-12 22:31
I see this is an old article and closed because it is supposedly fixed, however I just installed storefront 2.0.5 and I am having the same issues of the colors reverting back to default on my child theme.  

Has this issue not been fixed in the theme yet?   

Secondly, I see there is a fix by pasting code into the setup.php file, however I cannot seem to find that file on my server with my wordpress/theme install.  Where does this file exist?  I don't seem to have the path referenced in this post.

Thanks for the help!

**Comment by opportus** [comment] 2016-07-12 22:52
Since the release v2.0, the theme has been heavily restructured, no setup.php anymore. But you can find the enqueuing style functions [here](https://github.com/woothemes/storefront/blob/master/inc/class-storefront.php#L170).

**Comment by ArcodeFire** [comment] 2016-07-12 23:00
Thank you for the reply.

So as I understand it, this issue was not fixed in the latest version of storefront and I need to update code in the class-storefront.php to get my child theme to work properly?

If that is the case, then do I copy and past all of the code in the link your provided or just a snippet?  Please be specific so I fix the problem and don't make it worse.  

Thanks for the help!

**Comment by opportus** [comment] 2016-07-12 23:06
**I didn't mean that will fix your issue**. Anyway you shouldn't touch  the Storefront original files since your modifications will be deleted the next update. I mentioned this thinking you'll understand by yourself.
Just adapt your child theme or custom CSS to the new way Storefront is working.

**Comment by ArcodeFire** [comment] 2016-07-13 00:00
I have to disagree that it is working, which is the reason for my post....unless I have a special case here.

I created a storefornt child theme and my colors are reverting back once I view my site.  I did not have this issue until I created the child theme.  I fixed the header by modifying the .css file but I would rather not have to do that for all of the colors (backgrounds, links, texts, etc.) on my site.  

Is modifying the .css file that only fix?  If so, is there a list somewhere of all of the css code to make these modifications?

Thanks for your help!

**Comment by opportus** [comment] 2016-07-13 00:15
Are you manually loading your child theme main CSS file ? If  that's the case, try deleting the line enqueueing it in your functions.php.

**Comment by ArcodeFire** [comment] 2016-07-13 00:21
The only thing I did was click the Create Child Theme button on the Storefront 2.0.5 theme.  Ever since then, none of my color settings have been sticking.

**Comment by opportus** [comment] 2016-07-13 00:53
I don't understand where do you see this button ?

**Comment by ArcodeFire** [comment] 2016-07-13 00:55
![capture](https://cloud.githubusercontent.com/assets/20428254/16788423/f262b93a-4872-11e6-933b-9c0219e3156c.JPG)

**Comment by opportus** [comment] 2016-07-13 00:59
I don't have this button, are you sure it doesn't come from a tier unupdated plugin ?

**Comment by ArcodeFire** [comment] 2016-07-13 01:00
This is the auto generated code in my style.css file `@import url("../storefront/style.css");`

This is the custom code that I added to the custom css section to get my background to stay: `.site-header {
	background-color: #363545;
}`

Not sure what to do at this point...

**Comment by ArcodeFire** [comment] 2016-07-13 01:09
> I don't have this button, are you sure it doesn't come from a tier unupdated plugin ?

This is from the Wordpress theme page.  Click Themes under Appearance and then click Theme Details on Storefront and you will see the button on the bottom.  This is the only way I know how to create a child theme.  Is there another way?

![capture](https://cloud.githubusercontent.com/assets/20428254/16788671/e3065846-4874-11e6-86ba-2f950fa50ddf.JPG)

**Comment by ArcodeFire** [comment] 2016-07-13 01:13
Thank you for your continued help (sorry, I am a bit new to WP).

> try deleting the line enqueueing it in your functions.php

I do not see any enqueueing lines in my /themes/storefront/functions.php file.  Am I looking in the right file? 

Why do I feel like I have a completely different version of WordPress than you!?

**Comment by BurlesonBrad** [comment] 2016-07-15 01:13
@ArcodeFire Github is for **BUGS**, _**not support**_.  But before @jameskoster Locks and Limits this **issue** _(because some of us :heart: to see **closed** issues!)_, let's give this one last try :+1: 

#### Go to your admin area, WooCommerce > System Status
![woocommerce-system-status](https://cloud.githubusercontent.com/assets/6208757/16860358/1aa3ad56-49fd-11e6-825b-bce57d3eda0f.png)
#### Now click the button labelled "Get System Report" 
![get-system-report](https://cloud.githubusercontent.com/assets/6208757/16860405/901f09fe-49fd-11e6-8753-4bd00565306b.png)
#### Now click the button labelled "Copy For Support" 
_(which **again** is not what GitHub is for.  That **IS** what https://wordpress.org/support/theme/storefront **IS** for)_
![copy-for-support](https://cloud.githubusercontent.com/assets/6208757/16860459/0c2976ec-49fe-11e6-89cc-ac0c33608aea.png)
After you click the button labelled "Copy For Support" in the above screenshot, you'll get this tooltip:
![copy-for-support-copied](https://cloud.githubusercontent.com/assets/6208757/16860504/66ad6894-49fe-11e6-82ca-b87e533e8988.png)
The **NEXT** post _(before @jameskoster gets a chance to **Lock and Limit** this **issue** and move it to **"closed"**)_ needs to be you **pasting** your **System Report** information. :sunglasses:

**Comment by jameskoster** [comment] 2016-07-15 18:32
That child theme creation button is not coming from WordPress core.

> This is the auto generated code in my style.css file @import url("../storefront/style.css");

That is bad and will not work for Storefront. If you're running a child theme, Storefront automatically recognises this an loads the stylesheets for you. So remove that line.

> I created a storefornt child theme and my colors are reverting back once I view my site 

Switching themes resets your Customizer settings, FYI.

I'm locking this, please post in support if you're still having problems :)
