### ISSUE TITLE
Strange bugs on ipad ios

### ISSUE THREAD

**Issue by el-presidente** [woothemes/storefront#388] opened 2016-05-07 16:22 UTC
I have two might be bugs:

1) Might be a 'bug 40cm' as we say in Danish - that the bug is 40cm away from the screen - but I've had some customers complain that on iOS Safari iPad they couldn't add products. The last customer tried to add this product http://www.landhave.dk/produkt/plantekasser-paa-hjul-aflange/ - I suspect that they have a hard time actually choosing the attributes on the iPad and/or it might be a WooCommerce issue.

2) Like number one this might be WooCommerce issue but when I have chosen the first attribute, fx on http://www.landhave.dk/produkt/plantekasser-paa-hjul-aflange/ I want to use the native built in function '>' which should jump to the next attribute but it doesn't. The strange thing is if I've already chosen the first attribute and then return to this attribute the '>' works and jumps right on to the second attribute.

![img_6178](https://cloud.githubusercontent.com/assets/937382/15093161/296a8692-147f-11e6-92e7-f24b67eea182.PNG)

**Comment by jameskoster** [comment] 2016-05-09 08:59
Hey

1. Hehe, we have a similar expression - a 'PICNIC' - Problem In Chair Not In Computer xD I just tested this on my handheld devices and didn't have any issues adding products to the cart at all. A little more info might shed some light on this. What happens when they click the dropdowns? Can they select the options OK?

2. This is a WooCommerce issue. The problem is that the options are populated dynamically based on the first selection. If you open an issue on the WooCommerce repo we might be able to fix that.

Going to close this, but please re-open if the exact issue in the first problem becomes apparent.

**Closed by jameskoster** 2016-05-09 08:59 UTC
